export enum AnimeEndpoints {
  AnimeFullById = '/anime/{id}/full',
  AnimeById = '/anime/{id}',
  AnimeCharacters = '/anime/{id}/characters',
  AnimeStaff = '/anime/{id}/staff',
  AnimeEpisodes = '/anime/{id}/episodes',
  AnimeEpisodeById = '/anime/{id}/episodes/{episode}',
  AnimeNews = '/anime/{id}/news',
  AnimeForum = '/anime/{id}/forum',
  AnimeVideos = '/anime/{id}/videos',
  AnimeVideosEpisodes = '/anime/{id}/videos/episodes',
  AnimePictures = '/anime/{id}/pictures',
  AnimeStatistics = '/anime/{id}/statistics',
  AnimeMoreInfo = '/anime/{id}/moreinfo',
  AnimeRecommendations = '/anime/{id}/recommendations',
  AnimeUserUpdates = '/anime/{id}/userupdates',
  AnimeReviews = '/anime/{id}/reviews',
  AnimeRelations = '/anime/{id}/relations',
  AnimeThemes = '/anime/{id}/themes',
  AnimeExternal = '/anime/{id}/external',
  AnimeStreaming = '/anime/{id}/streaming',
  AnimeSearch = '/anime',
}
