export * from './anime-character.model'
export * from './anime-episode.model'
export * from './anime-picture.model'
export * from './anime-staff.model'
export * from './anime-statistics.model'
export * from './anime-video.model'
export * from './anime.model'
